# Script inspired from: https://dzfrias.dev/blog/deploy-rust-cross-platform-github-actions/

name: Deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build
        run: cargo build --verbose --release

      - name: Build archive
        shell: bash
        run: |
          # Replace with the name of your binary
          binary_name="scriptor"

          dirname="$binary_name-${{ env.VERSION }}"
          mkdir "$dirname"

          mv "target/${{ matrix.target }}/release/$binary_name" "$dirname"

          tar -czf "$dirname.tar.gz" "$dirname"
          echo "ASSET=$dirname.tar.gz" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.ASSET }}
